apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: jelly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - image: linuxserver/sonarr
        imagePullPolicy: Always
        name: sonarr
        ports:
        - containerPort: 8989
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - mountPath: "/config"
          readOnly: false
          name: nfs
          subPath: "pods_config/sonarr"
        - mountPath: "/tv"
          readOnly: false
          name: nfs
          subPath: "media/TVShows"
        - mountPath: "/downloads"
          readOnly: false
          name: nfs
          subPath: "media/Downloads"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: jellydata
