apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: jelly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - image: lscr.io/linuxserver/lidarr:develop
        imagePullPolicy: Always
        name: lidarr
        ports:
        - containerPort: 8686
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - mountPath: "/config"
          readOnly: false
          name: nfs
          subPath: "pods_config/lidarr"
        - mountPath: "/music"
          readOnly: false
          name: nfs
          subPath: "media/Music"
        - mountPath: "/downloads"
          readOnly: false
          name: nfs
          subPath: "media/Downloads"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: jellydata
