apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: jelly
spec:
  ports:
  - name: tdarr-web
    port: 8265
    protocol: TCP
    targetPort: 8265
  - name: tdarr-server
    port: 8266
    protocol: TCP
    targetPort: 8266
  - name: tdarr-internal
    port: 8267
    protocol: TCP
    targetPort: 8267
  selector:
    app: tdarr
