apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jelly
  namespace: jelly
  labels:
    app: jelly

resources:
  - namespace.yml
  - ingress.yml
  - pv.yml
  - pvc.yml
  - bazarr
  - jellyfin
  - jellyseerr
  - kavita
  - nzbget
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - sonarr
  - lidarr
  - flaresolverr
  - tdarr
