apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellydata
  namespace: jelly
spec:
  capacity:
    storage: 5000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: nfs-server
    path: "cluster-volume/jellydata"
