apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellydata
  namespace: jelly
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5000Gi
