apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-web-at-home
  namespace: web-at-home
spec:
  capacity:
    storage: 210Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: bl-fb-nas03
    path: "/volume1/k3s-cluster/web-at-home"
