apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-web-at-home
  namespace: web-at-home
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: nfs-server
    path: "cluster-volume/web-at-home"
