apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-at-home
  namespace: web-at-home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
