apiVersion: v1
kind: Service
metadata:
  labels:
    app: tandoor
    tier: database
  name: tandoor-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: tandoor
    tier: database
  sessionAffinity: None
  type: ClusterIP
