apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: jelly
spec:
  ports:
  - name: qbittorrent-tcp-web
    port: 8080
    targetPort: 8080
  - name: qbittorrent-tcp
    port: 6881
    targetPort: 6881
  - name: qbittorrent-udp
    port: 6881
    protocol: UDP
    targetPort: 6881
  selector:
    app: qbittorrent
