apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jelly
spec:
  ports:
  - name: jellyseerr-tcp
    port: 5055
    protocol: TCP
    targetPort: 5055
  selector:
    app: jellyseerr
