---
DNS1:
  10.0.0.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  ingressClassName: nginx-internal
  hosts:
    - "pihole.kube.lan"
serviceWeb:
  loadBalancerIP: 10.0.4.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 10.0.4.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
