apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
resources:
  - namespace.yml
  - ingress.yml
  - pv.yml
  - pvc.yml
  - deployment.yml
  - service.yml
