apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-gitea
  namespace: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: nfs-server
    path: "cluster-volume/gitea"
